sonar.projectKey=document-generator-api
sonar.projectName=document-generator-api
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java,src/main/resources
sonar.tests=src/test/java,src/test/resources
sonar.exclusions=build/**,gradle/**,kustomization/**,docs/**,wiremock/**,Dockerfile,catalog-info.yaml,tenposervice-values.yaml,tenposervice-private-values.yaml,mkdocs.yaml
sonar.coverage.exclusions=**/Application.java,**/config/**

sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test
sonar.junit.reportPaths=build/test-results/test
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
