apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: document-generator-api
  description: PDF document generator
  annotations:
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: document-generator-api

  links:
    - url: https://onenr.io/xxx #replace with link
      title: NewRelic APM
      icon: dashboard
    - url: https://tenpo-prod.kb.eastus2.azure.elastic-cloud.com:9243/app/r/s/xxx #replace with link
      title: Logs
      icon: TextSnippet
spec:
  type: service
  lifecycle: production
  owner:  group:default/channel-loyalty-team
  system: loyalty