selector:
  app: document-generator-api
networking:
  host: '${TENPO_SERVICE_PUBLIC_HOST}'
  port: 80
  protocol: TCP
  endpoints:
    - name: document-generator-api-public-endpoint
      path: /v1/document-generator-api
      profile: private
      methods:
        - GET
teamInfo:
  name: "group:default/channel-loyalty-team"