apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_NAME}
  annotations:
    meta.helm.sh/release-name: ${CI_PROJECT_NAME}
    meta.helm.sh/release-namespace: tenpo-document-generator-api
  labels:
    app.kubernetes.io/managed-by: "Helm"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ${CI_PROJECT_NAME}